import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}
const inter = Inter({ subsets: ["latin"] })

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <header className="sticky top-0 z-50 h-16 w-full border-b shadow backdrop-blur">
          <div className="mx-auto flex h-full max-w-7xl items-center justify-between px-4">
            <h1 className="text-2xl font-bold">Soloq Challenge 4eS</h1>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
